id: P000701
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4049
  title: རིག་འཛིན་ཀློང་གསལ་སྙིང་པོའི་གཏེར་བྱོན་སྐུ་གསུམ་ཆོ་གའི་རྒྱབ་དཀར།
  author: ''
  volumes:
    e9668f5e1a5a4c918439205d0c6da238:
      image_group_id: I3CN4233
      title: ''
      volume_number: 1
      total_pages: 217
      base_file: v001.txt
