id: I2BFD71CF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T23:02:16+00:00'
last_modified: '2022-06-07T12:41:53.006479+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4049
  title: རིག་འཛིན་ཀློང་གསལ་སྙིང་པོའི་གཏེར་བྱོན་སྐུ་གསུམ་ཆོ་གའི་རྒྱབ་དཀར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E3D4:
      image_group_id: I3CN4233
      title: ''
      total_pages: 217
      order: 1
      base_file: E3D4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
